---
title: "Wine Features"
author: "Your name here!"
date: "02/03/2025"

jupyter: python3

---

**Abstract:**

This is a technical blog post of **both** an HTML file *and* [.qmd file](src/wine_features_py.qmd) hosted on GitHub pages.

# Setup

1.  Change the author of this QMD file to be yourself and delete this line.
2.  Modify if necessary the below code so that you can successfully load `wine.rds` then delete this line.
3.  In the space provided after the Python chunk, explain what thecode is doing (line by line) then delete this line.
4.  Get your [GitHub Pages](https://docs.github.com/en/pages/quickstart) ready.

**Set Up Python:**
```{python}
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

from sklearn.linear_model import LinearRegression
from sklearn.model_selection import train_test_split
from sklearn.metrics import mean_squared_error
from sklearn.utils import resample
```

**Set Up R Compatability:**
```{python}
import pyreadr
```

**Step Up Dataframe:**
```{python}
url = 'https://cd-public.github.io/D505/dat/'
rds = 'wine.rds'
pyreadr.download_file(url + rds, rds) 
wine = pyreadr.read_r(rds)[None]      
```

**Explanataion:**

> <span style="color:red;font-weight:bold">TODO</span>: *write your line-by-line explanation of the code here*

# Feature Engineering

We begin by engineering an number of features.

1. Create a total of 10 features (including points). 
2. Remove all rows with a missing value. 
3. Ensure only log(price) and engineering features are the only columns that remain in the `wino` dataframe.

```{python}
wine['lprice'] = wine['price'].apply(lambda x: np.log(x))
```

# Skelarn

We now use a train/test split to evaluate the features.

1. Use the Sklearn library to partition the wino dataframe into an 75/25 split. 
2. Run a linear regression with bootstrap resampling. 
3. Report RMSE on the test partition of the data.

```{python}
# TODO: hint: Check the slides.
```

# Variable selection

We now graph the importance of your 10 features.

```{python}
# TODO: hint: Check the slides.
```