---
title: "Machine Learning Overview"
subtitle: "Applied Machine Learning"
author: "Jameson > Hendrik > Calvin"

format:
    html

execute:
    echo: true
    freeze: true  # never re-render during project render
---

## Libraries

- I'll just include them upfront.
```{r}
library(tidyverse)
library(moderndive)
library(caret)
library(dslabs)
# Just for the slides
library(thematic)
theme_set(theme_dark())
thematic_rmd(bg = "#111", fg = "#eee", accent="#eee")
```

## Setup

- We will work with a `wine` dataset that is enormous.
  - Just to render a bit quickly, I take a sample.
  - You are welcome to work with the [full dataset](https://github.com/cd-public/DSLM-505/blob/master/dat/wine.rds)!

```{r}
wine_all = readRDS("../../dat/wine.rds")
# performance concession
wine = wine_all[sample(nrow(wine_all), 1000), ]
summary(wine_all)
```

# Review of Regression

## Single Variable

- Pick the poshest province.
```{r}
wine <- wine %>% 
  mutate(bordeaux=(province=="Bordeaux"))
```
- Take a quick regression model over the wine.
```{r}
m1 <- lm(price ~ points, data = wine)
pts <- data.frame(points=min(wine$points):max(wine$points))

wine <- wine %>% mutate(m1=predict(m1))
predict(m1)
```